name: Sonar qube analysis
on:
  push: 
    branches: [ tutorial-1 ]
  pull_request:
    branches: [ tutorial-1 ]

jobs:
  test-go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.27.1'
      - name: Run tests golang app
        run: go test ./...
      
      - name: Run tests with coverage
        run: |
          go test -coverprofile=coverage.out ./...



  # sonarqube:
  #   needs: test-go
  #   name: sonarqube scan
  #   runs-on: ubuntu-latest
  #   steps:  
  #     - uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
  #     - name: Run tests with coverage
  #       run: |
  #         go test -coverprofile=coverage.out ./...
  #     - uses: sonarsource/sonarqube-scan-action@master
  #       env:
  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  #         SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}  


  # trivy:
  #   name: Trivy scan
  #   # needs: sonarqube
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
 
  #     - name: Run Trivy (filesystem scan)
  #       uses: aquasecurity/trivy-action@v0.36.0
  #       with:
  #         scan-type: fs
  #         scan-ref: .
  #         scanners: vuln,secret,misconfig
  #         severity: HIGH,CRITICAL
  #         ignore-unfixed: true
  #         exit-code: "1" 
  #         format: table
  build:
    name: Build
    runs-on: ubuntu-latest
    # needs: [lint, test, trivy]
    steps:
      - uses: actions/checkout@v4
 
      - uses: actions/setup-go@v5
        with:
          go-version: '1.27.1'
          go-version-file: go.mod
          cache: true
 
      - name: Build
        run: go build -v ./...
