name: Sonar qube analysis
on:
  push: 
    branches: [ tutorial-1 ]
  pull_request:
    branches: [ tutorial-1 ]

jobs:
  test-go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.27.1'
      - name: Run tests golang app
        run: go test ./...
      
      - name: Run tests with coverage
        run: |
          go test -coverprofile=coverage.out ./...

  sast-check:
    needs: test-go
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.1'
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...


  # sonarqube:
  #   needs: sast-check
  #   name: sonarqube scan
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
  #     - name: Run tests with coverage
  #       run: |
  #         go test -coverprofile=coverage.out ./...
  #     - uses: sonarsource/sonarqube-scan-action@master
  #       env:
  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  #         SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}  